# Generated by Django 5.0.2 on 2025-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
