# Generated by Django 5.0.2 on 2025-05-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0003_siir_likes_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siir',
            options={'ordering': ('-olusturma_tarihi',), 'verbose_name_plural': 'Şiirler'},
        ),
        migrations.AddField(
            model_name='siir',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı')], default='draft', max_length=10),
        ),
    ]
