# Generated by Django 5.0.2 on 2025-05-24 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siir',
            name='likes',
        ),
        migrations.AddField(
            model_name='siir',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_siirler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Beğeni'), ('comment', 'Yorum'), ('follow', 'Takip'), ('save', 'Kaydetme')], max_length=10),
        ),
    ]
