# Generated by Django 5.0.2 on 2025-05-24 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0007_remove_siir_likes_siir_saved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siir',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_siirler', to=settings.AUTH_USER_MODEL),
        ),
    ]
