# Generated by Django 5.0.2 on 2025-05-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siirler', '0008_siir_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
    ]
